# WEB PROPERTIES
# 接口测试页面 swagger-ui.html
server:
  port: 5008
  context-path: '/'

# SPRING
spring:
  # DATASOURCE
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/shangair?useUnicode=true&characterEncoding=UTF-8'
    username: root
    password: admin@123

  # JPA
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: false

# 自定义配置
dtu-server-port: 5006

kafka:
  broker-list: HighPressData01:9092,HighPressData02:9092,HighPressData03:9092
  row-topic: shangair_rawdata
  data-topic: shangair_metrics

hbase:
  zookeeper-quorum: HighPressData01,HighPressData02,HighPressData03
  zookeeper-port: 2181